sonar.projectKey=MFAI-Monorepo
sonar.projectName=Money Factory AI
sonar.projectVersion=1.0

# Chemins des sources
sonar.sources=journey-simulator/src,mf-back,web

# Exclusions Globales (Ignore tout ce qui commence par 'data')
sonar.exclusions=data/**,**/node_modules/**,**/dist/**,**/build/**,**/.next/**,**/tests/**

# Exclusions spécifiques au moteur JavaScript/TypeScript
sonar.javascript.exclusions=data/**,**/node_modules/**
sonar.typescript.exclusions=data/**,**/node_modules/**

# Encodage
sonar.sourceEncoding=UTF-8
