import { useState } from 'react';
import { ArtifactCard } from './ArtifactCard';
import { ArtifactModal } from './ArtifactModal';
import { useArtifacts } from '../../hooks/useArtifacts';

export const ProjectAssets = () => {
  const [selectedArtifact, setSelectedArtifact] = useState<any>(null);
  const { artifacts, loading, error } = useArtifacts();

  if (loading) {
    return (
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <h2 className="text-xl font-display font-bold text-white">Project Artifacts</h2>
          <span className="text-xs text-purple-400 border border-purple-500/30 px-2 py-1 rounded bg-purple-500/10">
            Generated by Zyno
          </span>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          {[1, 2, 3, 4].map((i) => (
            <div
              key={i}
              className="p-4 rounded-xl border bg-white/5 border-white/5 animate-pulse h-40"
            >
              <div className="h-4 bg-white/20 rounded mb-3 w-3/4"></div>
              <div className="h-3 bg-white/10 rounded mb-2 w-full"></div>
              <div className="h-3 bg-white/10 rounded w-1/2"></div>
            </div>
          ))}
        </div>
      </div>
    );
  }

  if (error) {
    console.error('Error loading artifacts:', error);
    return (
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <h2 className="text-xl font-display font-bold text-white">Project Artifacts</h2>
          <span className="text-xs text-purple-400 border border-purple-500/30 px-2 py-1 rounded bg-purple-500/10">
            Generated by Zyno
          </span>
        </div>
        <div className="text-red-400">Error loading artifacts: {error}</div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h2 className="text-xl font-display font-bold text-white">Project Artifacts</h2>
        <span className="text-xs text-purple-400 border border-purple-500/30 px-2 py-1 rounded bg-purple-500/10">
          Generated by Zyno
        </span>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {artifacts.map((artifact) => (
          <ArtifactCard
            key={artifact.id}
            artifact={artifact}
            onClick={() => setSelectedArtifact(artifact)}
          />
        ))}
      </div>

      <ArtifactModal
        isOpen={!!selectedArtifact}
        onClose={() => setSelectedArtifact(null)}
        fileUrl={selectedArtifact?.fileUrl || ''}
        title={selectedArtifact?.title || ''}
      />
    </div>
  );
};
