// 📄 agents/AgentTemplate.js

const { getRagSnippets, ingestDocumentsIfNeeded } = require('../rag/ragClient');
const { createAgentResponse } = require('./telemetryUtils');

module.exports = async function AgentTemplate(agentInput = {}, context = {}) {
  const agentName = 'AgentTemplate';
  const user = agentInput.user || context.user || { id: 'demo_user' };
  const phase = agentInput.phase || context.phase || 'Discover';
  const objective =
    agentInput.objective || context.objective || agentInput.input || context.input || `Phase ${phase}`;

  const ragSnippets = await getRagSnippets({ query: objective, userContext: user });
  const ingestedDocuments = await ingestDocumentsIfNeeded({ userId: user.id || user.userId || 'demo_user', phase });

  const generatedResponse =
    `Agent ${agentName} has analyzed the data and recommends studying ${ragSnippets[0]?.title || 'the provided documents'}.`;

  return createAgentResponse(agentName, {
    phase,
    intent: context.intent || agentInput.intent || null,
    objective,
    prompt: `Quick synthesis of useful data for ${phase}`,
    reasoning: 'Initial mission analysis to identify the most relevant resources.',
    action: "Select key resources and launch the next agent if necessary.",
    summary: `Result generated by ${agentName}`,
    outcome: 'pending',
    payload: {
      message: generatedResponse,
      ingestedDocuments,
    },
    snippets: ragSnippets,
    ingestedDocuments,
    metrics: { confidence: 0.8, success: true, impact: 'medium' },
    user,
  });
};
