module.exports = [
  {
    agentId: 'SecurityAuditAgent',
    domain: 'security',
    capabilities: ['audit', 'risk', 'compliance'],
    intents: ['security_audit', 'default'],
    toolsAllowed: [],
    llmProfile: { model: 'gpt-4o', temperature: 0.2 },
    ragProfile: { topK: 4 },
    inputSchema: { type: 'object', required: ['input'] },
    outputSchema: { type: 'object', required: ['summary', 'findings'] },
    confidenceWeight: 1.0,
    requiresRag: true,
    maxTokens: 800,
    timeoutMs: 6000,
    priority: 90,
  },
  {
    agentId: 'ProductSpecAgent',
    domain: 'product',
    capabilities: ['spec', 'flows', 'acceptance'],
    intents: ['product_spec', 'default'],
    toolsAllowed: [],
    llmProfile: { model: 'gpt-4o', temperature: 0.2 },
    ragProfile: { topK: 4 },
    inputSchema: { type: 'object', required: ['input'] },
    outputSchema: { type: 'object', required: ['summary', 'flows', 'acceptance'] },
    confidenceWeight: 1.0,
    requiresRag: true,
    maxTokens: 800,
    timeoutMs: 6000,
    priority: 80,
  },
  // Legacy agents can be added here incrementally with their intent mapping.
];
