import { existsSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const projectRoot = join(__dirname, '..')

const fixes = [
  {
    filename: 'define-globalThis-property.js',
    redirect: './define-global-property.js'
  },
  {
    filename: 'globalThis-this.js',
    redirect: './global-this.js'
  }
]

for (const { filename, redirect } of fixes) {
  const target = join(projectRoot, 'node_modules', 'core-js', 'internals', filename)
  if (existsSync(target)) {
    continue
  }

  const banner = '// Auto-generated by scripts/postinstall-fixes.mjs to patch missing core-js internals\n'
  const content = `${banner}module.exports = require('${redirect}');\nmodule.exports.default = module.exports;\n`

  try {
    writeFileSync(target, content, 'utf8')
  } catch (error) {
    console.warn(`[postinstall-fixes] Unable to create ${filename}:`, error)
  }
}
